spring:
  application:
    name: "gatewayserver"

  config:
    import: "optional:configserver:http://localhost:8071/"

#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Flag that enables DiscoveryClient gateway integration.
          lower-case-service-id: true # Option to lower case serviceId in predicates and filters, defaults to false. Useful with eureka when it automatically uppercases serviceId. so MYSERIVCE, would match /myservice/**
      httpclient:
        connect-timeout: 1000 # 1 second
        response-timeout: 2s

#      routes:
#        - id: accounts_route
#          uri: lb://ACCOUNTS
#          predicates:
#            - Path=/linsbank/accounts/**
#          filters:
#            - RewritePath=/linsbank/accounts/(?<segment>.*), /$\{segment}
#            - AddResponseHeader=X-Response-Time, '${java.time.LocalDateTime.now()}' //todo: !!!!!!can not get time with this expression, use Method2!!!!!!!
#
#        - id: loans_route
#          uri: lb://LOANS
#          predicates:
#            - Path=/linsbank/loans/**
#          filters:
#            - RewritePath=/linsbank/loans/(?<segment>.*), /$\{segment}
#            - AddResponseHeader=X-Response-Time, '${java.time.LocalDateTime.now()}'
#
#        - id: cards_route
#          uri: lb://CARDS
#          predicates:
#            - Path=/linsbank/cards/**
#          filters:
#            - RewritePath=/linsbank/cards/(?<segment>.*), /$\{segment}
#            - AddResponseHeader=X-Response-Time, '${java.time.LocalDateTime.now()}'

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Lin's Bank Gateway server Application"
    version: "1.0.0"

logging:
  level:
    com:
      udemy:
        gatewayserver: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
