spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "welcome to Lin's Bank accounts related local APIs."
  contactDetails:
    name: "Chen - PM"
    email: "totoro@gmail.com"
  onCallSupport:
    - 10242-31234
    - 23434-25432